### PR TITLE
I translated into Japanese.

### PR DESCRIPTION
**Pull request by zqvjhr1103**
I translated it into Japanese from scratch based on "TsunKitTranslations/en/kcnav.json".

The translation was done based on my own experience of using it and the following pages.
https://wikiwiki.jp/kancolle/%E3%83%AB%E3%83%BC%E3%83%88%E5%88%86%E5%B2%90#how_to_kcnav
(By the way, I wrote this page・。・ｖ)

The pioneer has translated the ship class list in "Ship Classes" into Japanese, but I think it is fine to leave it in English.
One of the reasons is that the search is done using the English ship class name.
The second reason is that Japanese admirals often mistake "潜空"(SSV:潜水空母) and "潜母"(AS:潜水母艦). Abbreviations of ship types in Japanese are ambiguous and should be avoided.
Instead, I suggest that each ship type in the "Ship Classes" have a tooltip with a Japanese translation. I've already added a tip for the Japanese translation of the ship classes in the json I pull request.

Also, I couldn't come up with a good Japanese translation, so I added new explanatory tooltips to "mapMenu", "panelStatsFSRadar", etc.

I apologize for adding tooltips in places where there were originally no tips.

I writed this sentence using a translating machine. Apologize if the rude expression.

Also, I'm new to GitHub, so there may be mistakes.

I have a question, can I still use the English version after the Japanese version comes?
I'm used to the English version and the display looks more stylish in English, so I would like to continue using the English version.

### CODE REVIEW

**Comment by sinsinpub** [comment]
personally I agree with using en ship-type terms in all cases. because I guess it is difficult to be typed and handled as filter criteria in translated terms, even in abbr.

**Comment by planetarian** [comment]
Just to clarify: filtering by ship class can be done using either the japanese or english class names, regardless of selected language.

I'm fine with this change, however! I'll start working on getting this resolved and merged in the morning, and will add the necessary references so that the tooltips can function.

Thanks for your contribution!

**Comment by zqvjhr1103** [comment]
Thank you both for your reply.

I didn't know that you could search for ship type names in Japanese. My apologies.

Thank you for accepting my suggestion!

**Comment by planetarian** [comment]
> I have a question, can I still use the English version after the Japanese version comes?
> I'm used to the English version and the display looks more stylish in English, so I would like to continue using the English version.

You certainly can! There is a selector at the top-right of the page:
image

You can click the `A` or `あ` to instantly change languages to English or Japanese, or you can use the dropdown to select from any of the available languages.

**Comment by planetarian** [comment]
Since we had three PR submissions at the same time, I took some time to merge them, taking parts I liked from all three. There might have been different translation styles for things, which may necessitate some review for consistency, but in terms of layout and conciseness, I think this will work fairly well. Feel free to do further review and adjustment of the merged file if you desire.

**Pull request merged**
