### PR TITLE
Update Japanese translations and suggestions

### PR DESCRIPTION
**Pull request by sinsinpub**
Suggest:
 * Also update `lang` attribute on `<html>` tag, for Japanese, update it from `en` to `ja`. It helps to correct browser controls' language detection, like the datetime picker.
 * Give a method to override html and body's `font-family` style. Perhaps, just allow us to add a special `font-family` term into json?
   For CJK languages, alternative font families required since browser can't do precise detection. Sample screenshot when I add `Meiryo UI`: (`font-family: Verdana, Arial, "Hiragino Kaku Gothic ProN", "Hiragino Sans", "Meiryo UI", sans-serif;` is used) 
image

Didn't notice #3, leave refining/merging to u guys.

### CODE REVIEW

**Comment by planetarian** [comment]
seems like there are some encoding shenanigans to deal with; chromium's JS engine doesn't like JSON with UTF8 BOM, but it's fine with normal UTF8? this threw me for a loop for a bit when attempting to test.

**Comment by planetarian** [comment]
Excellent suggestions re: lang/fonts! I will implement this ASAP.

**Comment by sinsinpub** [comment]
should be fine to remove BOM. I left it untouched, perhaps somebody's editor auto saved with BOM? could mention file encoding in readme too

**Comment by planetarian** [comment]
I have updated KCNav to automatically update the HTML lang attribute based on the selected language. I've also added support for locale-specific CSS, so font customization (and any other locale-specific style) can simply be added to kcnav.css. Sound good?

**Pull request merged**
